languageCode = "en"
languageName = "English"
weight = 1
title = "Juu's Blog"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
description = "My awesome website"
dateFormat = "2 January 2006"
author = { name = "Hu, Jun", image = "img/avatar.png", headline = "My blogs", bio = "A little bit about you", links = [{ github = "https://github.com/JuuHuu" } ] }
