[[main]]
name = "Posts"
pageRef = "posts"
weight = 10

[[main]]
name = "Tags"
pageRef = "tags"
weight = 20

[[main]]
name = "Series"
pageRef = "series"
identifier = "vWeCzvz3V1"
weight = 9999

#[[footer]]
#name = "Tags"
#pageRef = "tags"
#weight = 10
